name: 'Deploy to AWS S3'
description: 'Deploy a static website to AWS S3'
inputs:
  bucket:
    description: 'S3 bucket name'
    required: true
  bucket-region:
    description: 'Region of the bucket'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'Folder containing deploy files'
    required: true
runs:
  using: 'node16'
  main: 'main.js'